apiVersion: v1
kind: PersistentVolume
metadata:
    name: jenkins-pv
spec:
    capacity: 
        storge: 10Gi
    accessModes: 
        - ReadWriteOnce
    awsElasticBlockStore:
        fsType: ext4
        volumeID: vol-04d40641da187cd8f